// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");

function str(prim) {
  return prim;
}

var logo = (require('./assets/Logo.png'));

var headerImgae = (require('./assets/anugraha.jpg'));

var ar01 = (require('./assets/ARCHITECTURE/01.jpg'));

var ar02 = (require('./assets/ARCHITECTURE/02.png'));

var ar03 = (require('./assets/ARCHITECTURE/03.jpg'));

var ar04 = (require('./assets/ARCHITECTURE/04.jpg'));

var i01 = (require('./assets/INTERIOR/01.jpg'));

var i02 = (require('./assets/INTERIOR/02.jpg'));

var i03 = (require('./assets/INTERIOR/03.jpg'));

var i04 = (require('./assets/INTERIOR/04.jpg'));

var i05 = (require('./assets/INTERIOR/05.jpg'));

var i06 = (require('./assets/INTERIOR/06.jpg'));

var i07 = (require('./assets/INTERIOR/07.jpg'));

var i08 = (require('./assets/INTERIOR/08.jpg'));

var i09 = (require('./assets/INTERIOR/09.jpg'));

var b01 = (require('./assets/BACKWATERS/01.jpg'));

var b02 = (require('./assets/BACKWATERS/02.jpg'));

var b03 = (require('./assets/BACKWATERS/03.jpg'));

var b04 = (require('./assets/BACKWATERS/04.jpg'));

function renderText(caption, description) {
  return React.createElement("div", {
              className: "md:flex w-full md:mt-8 mt-4 py-4"
            }, React.createElement("div", {
                  className: "md:w-2/5 md:text-4xl text-2xl"
                }, caption), React.createElement("div", {
                  className: "md:w-3/5 md:text-xl text-md md:pt-0 pt-2"
                }, $$Array.map((function (para) {
                        return React.createElement("p", {
                                    key: para,
                                    className: "pt-4"
                                  }, para);
                      }), description)));
}

function renderForm(param) {
  return React.createElement("form", {
              className: "max-w-xl",
              id: "contactform",
              action: "https://formspree.io/contact@anugrahakerala.com",
              method: "POST"
            }, React.createElement("div", {
                  className: "w-full mt-4"
                }, React.createElement("input", {
                      className: "name appearance-none h-10 mt-1 block w-full text-gray-800 border border-gray-400 rounded py-2 px-4 text-sm bg-gray-100 hover:bg-gray-200 focus:outline-none focus:bg-white focus:border-primary-400",
                      id: "name",
                      name: "name",
                      placeholder: "Enter your name",
                      required: true,
                      type: "text"
                    })), React.createElement("div", {
                  className: "w-full mt-4"
                }, React.createElement("input", {
                      className: "email appearance-none h-10 mt-1 block w-full text-gray-800 border border-gray-400 rounded py-2 px-4 text-sm bg-gray-100 hover:bg-gray-200 focus:outline-none focus:bg-white focus:border-primary-400",
                      id: "email",
                      name: "email",
                      placeholder: "Enter your email",
                      required: true,
                      type: "email"
                    })), React.createElement("div", {
                  className: "w-full mt-4"
                }, React.createElement("input", {
                      className: " appearance-none h-10 mt-1 block w-full text-gray-800 border border-gray-400 rounded py-2 px-4 text-sm bg-gray-100 hover:bg-gray-200 focus:outline-none focus:bg-white focus:border-primary-400",
                      id: "subject",
                      name: "subject",
                      placeholder: "Subject",
                      required: true,
                      type: "text"
                    })), React.createElement("div", {
                  className: "w-full mt-4"
                }, React.createElement("textarea", {
                      className: "message appearance-none mt-1 block w-full text-gray-800 border border-gray-400 rounded py-2 px-4 text-sm bg-gray-100 hover:bg-gray-200 focus:outline-none focus:bg-white focus:border-primary-400",
                      id: "message",
                      name: "message",
                      placeholder: "Your message",
                      required: true,
                      rows: 3
                    })), React.createElement("input", {
                  className: "Submit flex-none bg-gray-900 uppercase hover:bg-gray-600 focus:outline-none focus:bg-primary-800 text-sm text-white font-bold py-2 px-6 tracking-normal rounded-lg mt-4",
                  type: "submit",
                  value: "Send Message"
                }));
}

function renderlines(description) {
  return React.createElement("div", undefined, $$Array.map((function (para) {
                    return React.createElement("p", {
                                key: para
                              }, para);
                  }), description));
}

function renderHeading(heading) {
  return React.createElement("div", {
              className: "md:mt-10 mt-4 md:text-5xl text-3xl"
            }, heading);
}

function renderTwoImages(image1, image2) {
  return React.createElement("div", {
              className: "md:flex"
            }, React.createElement("img", {
                  className: "md:w-1/2 md:pr-2 md:mt-4 mt-4 md:h-full",
                  alt: image1,
                  src: image1
                }), React.createElement("img", {
                  className: "md:w-1/2 md:pl-2 md:mt-4 mt-4 md:h-full",
                  alt: image2,
                  src: image2
                }));
}

function renderThreeImages(image1, image2, image3) {
  return React.createElement("div", {
              className: "md:flex md:mt-2 md:-mr-5"
            }, React.createElement("img", {
                  className: "md:w-1/3 md:pr-5 mt-4 md:h-full",
                  alt: image1,
                  src: image1
                }), React.createElement("img", {
                  className: "md:w-1/3 md:pr-5 mt-4 md:h-full",
                  alt: image2,
                  src: image2
                }), React.createElement("img", {
                  className: "md:w-1/3 md:pr-5 mt-4 md:h-full",
                  alt: image3,
                  src: image3
                }));
}

function Home(Props) {
  return React.createElement("div", undefined, React.createElement("section", {
                  className: "md:py-10 pt-10 pb-4"
                }, React.createElement("div", {
                      className: "text-center"
                    }, React.createElement("div", {
                          className: "flex justify-center clearfix px-4 md:pb-10 pb-4"
                        }, React.createElement("img", {
                              className: "float-center",
                              alt: "logo",
                              src: logo
                            }))), React.createElement("div", {
                      className: "mt-4"
                    }, React.createElement("img", {
                          alt: "logo",
                          src: headerImgae
                        })), React.createElement("div", {
                      className: "md:flex w-full md:mt-10 mt-4 py-4 pb-1"
                    }, React.createElement("div", {
                          className: "md:w-2/5 md:text-4xl text-2xl md:-mt-2"
                        }, "A BOUTIQUE HOMESTAY"), React.createElement("div", {
                          className: "md:w-3/5 md:text-xl text-md md:pt-0 pt-2"
                        }, "Anugraha is an elegant homestay in Aymanam, in the central Kerala district of Kottayam. Located near the popular lakefront tourist spot of Kumarakom, this house along the Meenachil River backwaters is an ode to slow living, Keralan hospitality and the natural splendours of this tropical travel destination."))), React.createElement("section", {
                  className: "md:py-4pt-10 pb-4"
                }, renderTwoImages(ar01, ar04), renderTwoImages(ar02, ar03), renderText("THE VILLA", /* array */[
                      "Guests will stay in an independent villa, attended by two members of the house-staff. We take just one booking at a time, in order to ensure guests have our full attention and care. Think of a stay at Anugraha as a holiday visit to a friend's home in the Kerala countryside.",
                      "The Villa is a heritage home, constructed more than a century ago. It was restored under the direction of architect Bijoy Jain of Studio Mumbai and styled with contemporary art from the family's private collection, and an edit of design objects."
                    ]), React.createElement("div", {
                      className: "md:flex w-full"
                    }, React.createElement("div", {
                          className: "md:w-2/5 md:text-4xl text-2xl md:-mt-2"
                        }), React.createElement("div", {
                          className: "md:w-3/5 md:text-xl text-md md:pt-0 pt-2"
                        }, "There's plenty of quiet and privacy when you prefer, but when you'd rather not be alone then we invite you to take in the sights and sounds of the thriving estate, which is inhabited by the family that runs Anugraha, and includes their three dogs, Google, Zuma and Pepper. The 7.5 - acre property is punctuated by canals, a pond, vegetable garden, many varieties of tropical fruit trees, hardwoods, bamboo, and various kinds of ferns, designed and laid out by award-winning landscape architect Tom Stuart-Smith. ", React.createElement("div", {
                              className: "pt-4"
                            }, "A literary factoid: Aymanam village is the setting of Arundhati Roy's 1997 Booker Prize-winning novel ", React.createElement("span", {
                                  className: "italic"
                                }, "The God of Small Things. ")), React.createElement("div", {
                              className: "pt-4"
                            }, "Being in the tropical countryside, there are charming multilegged creatures everywhere; they mean no harm and they are an essential part of the life cycle of our part of the world.")))), React.createElement("section", {
                  className: "md:py-4pt-10 pb-4"
                }, renderThreeImages(i01, i02, i03), renderThreeImages(i04, i05, i06), renderThreeImages(i07, i08, i09), renderText("FACILITIES", /* array */[
                      "The Villa can house up to six people, between a Master Bedroom with a Queen-size bed, and the Attic Room, which has a Queen-size bed and two single beds, plus an en suite bathroom. While public areas like the living and dining rooms do not have air-conditioning, the bedrooms are airconditioned. And there's WIFI, of course. The property is perfectly suited for a couple, a family of four or six, or a party of six.",
                      "A bathroom enclosure on the ground floor is open-roofed and designed for separate but common use among the guests staying the villa.",
                      "The home also has a little study room and a well-appointed kitchen."
                    ])), React.createElement("section", {
                  className: "-mt-10"
                }, renderText("DINING", /* array */[
                      "At Anugraha, we serve traditional Keralan food in the style of the Syrian Christian community, to which the homeowners belong. The food of our region can be deliciously vegan, with the generous use of coconut, rice and vegetables, or the complete opposite, with plenty of seafood and beef. It can be as spicy as it should be, or as spicy as you prefer. Please let us know at the time of reservation if you have any particular restrictions, and we will do our best to accommodate requests. ",
                      "Those who wish to cook occasionally may do so, and we are happy to advise. You may use anything from the organic kitchen garden, which has seasonal herbs and vegetables throughout the year. The larder is well-stocked with the basics (milk, bread, eggs) plus a wide choice of teas, and coffee."
                    ])), React.createElement("section", {
                  className: "md:py-4pt-10 pb-4"
                }, renderTwoImages(b01, b02), renderTwoImages(b03, b04), renderText("THINGS TO DO", /* array */[
                      "The property has a swimming pool that is suitable for adults and children. It is located within a pool house that also contains a massage room where, upon request, we can arrange for a traditional therapeutic Keralan massage.",
                      "The vast greens of the property and the village offer great prospects for long walks, and birdwatching.",
                      "Villa Anugraha is located along the backwaters, within some of the most beautiful boating routes in the state. Take a languorous ride along the canals in a snake boat, captained by a local boatman.",
                      "Birds are the constant background choir of this estate. If you'd like to see the songsters then there are plenty of opportunities to sight families of kingfisher, schoolboy warbler, woodpecker, egret, duck, heron, Brahminy eagle, and many other species."
                    ])), React.createElement("section", {
                  className: "-mt-10"
                }, renderText("GETTING HERE", /* array */["The airport nearest to us is the Cochin International Airport, which is 2.5 hours away. Upon request, we can arrange for pick-up and drop-off to the airport."])), React.createElement("section", {
                  className: "md:py-4pt-10 pb-4"
                }, renderText("GET IN TOUCH", /* array */[
                      "For more information and further details, please write to contact@anugrahakerala.com or give us a call on +9194956 31122.",
                      "Follow us on Instagram via @anugrahakerala."
                    ]), React.createElement("div", {
                      className: "md:flex w-full md:-mt-10 -mt-4 mt-4 py-4"
                    }, React.createElement("div", {
                          className: "md:w-2/5 md:pt-0 pt-2 justify-right"
                        }), React.createElement("div", {
                          className: "md:w-3/5 md:text-xl text-md md:pt-0 pt-2 justify-right mt-4"
                        }, renderForm(/* () */0), React.createElement("div", {
                              className: "pt-6 pb-2 text-2xl font-semibold "
                            }, "ADDRESS"), renderlines(/* array */[
                              "Anugraha Puthenpurayil",
                              "Prapuzha Kadavu",
                              "Pulikkuttissery PO",
                              "Aimanam.",
                              "Kottayam 686015",
                              "Kerala, India"
                            ])))), React.createElement("section", {
                  className: "md:py-4pt-10 pb-4"
                }, renderText("CREDIT", /* array */["We are grateful to our friends who photographed Anugraha: Ashish Sahi, Derry Moore, and Wei Leng Tay."])));
}

var make = Home;

exports.str = str;
exports.logo = logo;
exports.headerImgae = headerImgae;
exports.ar01 = ar01;
exports.ar02 = ar02;
exports.ar03 = ar03;
exports.ar04 = ar04;
exports.i01 = i01;
exports.i02 = i02;
exports.i03 = i03;
exports.i04 = i04;
exports.i05 = i05;
exports.i06 = i06;
exports.i07 = i07;
exports.i08 = i08;
exports.i09 = i09;
exports.b01 = b01;
exports.b02 = b02;
exports.b03 = b03;
exports.b04 = b04;
exports.renderText = renderText;
exports.renderForm = renderForm;
exports.renderlines = renderlines;
exports.renderHeading = renderHeading;
exports.renderTwoImages = renderTwoImages;
exports.renderThreeImages = renderThreeImages;
exports.make = make;
/* logo Not a pure module */
